Play travis
Otus-DevOps-2018-02/ValeriyTuev_infra pull request #2
Opened 2018-03-18 19:05 UTC by ValeriyTuev

Add integration with travis.

2018-03-21 14:29 UTC, serjs reviewed
Привет! Увидел в канале интеграцию и сообщения, PR можно мержить, но только после того как расправишься с Homework-2. 👍

Влей второе задание и мы сможем расправиться с этим 😉 

Прошу прощения за задержку в проверке ДЗ

2018-03-22 10:49 UTC, vitkhab requested changes
Для сдачи ДЗ удали, пожалуйста, мусорный файл  `test.py` в корне репозитория.

В остальном все хорошо.

2018-04-01 16:49 UTC, ValeriyTuev commented
Done.

2018-04-06 10:27 UTC, Nklya commented
Лишний test.py находится в корне репозитория

2018-04-06 10:38 UTC, vitkhab approved these changes

2018-04-08 17:54 UTC, merged