Cloud testapp
Otus-DevOps-2018-02/ValeriyTuev_infra pull request #4
Opened 2018-07-09 20:27 UTC by ValeriyTuev

# Выполнено ДЗ № 5

 - [ ] Выполнено основное задание: поставил приложение, проверил его работоспособность, закомиттил скрипты install_ruby.sh, 
install_mongodb.sh и deploy.sh. 
 - [ ] Дополнительное задание: закомиттил скрипт startup-script.sh, для 
добавления к команде в gcloud. Команда для создания, используя скрипт:
gcloud compute instances create reddit-app\ 
--boot-disk-size=10GB \
--image-family ubuntu-1604-lts \
--image-project=ubuntu-os-cloud \
--machine-type=g1-small \
--tags puma-server \
--restart-on-failure \
--metadata-from-file startup-script=%PATH%\startup-script.sh

Создать правило firewall из консоли. Для тестового приложения команда 
выглядит так:
gcloud beta compute firewall-rules create default-puma-server\ 
--action allow \
--target-tags puma-server \
--source-ranges 0.0.0.0/0 \
--rules tcp:9292

## В процессе сделано:
 - 1. Создана виртуальная машина с тестовым приложение
 - 2. Добавлено правило для тестового приложения.
 - 3. Добавлены скрипты для автоматического разворачивания как отдельных приложений, так и полностью виртуальной машины с приложением целиком.

## Как запустить проект:
 Копируем себе скрипт startup-script.sh, запускаем команду для создания 
VM, указав путь к скрипту, команда дана выше.

## Как проверить работоспособность:
 Смотрим в консоли адрес получившейся машины и идем по ссылке 
http://hostIP:9292

## PR checklisk
 - [x ] Выставил label с номером домашнего задания
 - [x ] Выставил label с темой домашнего задания

2018-07-10 07:57 UTC, Nklya requested changes
Добрый день.

Валерий, тесты не проходят потому что:
1. Скрипты должны быть закоммичены с признаком что они исполнимые (+х)
2. Файлы из предыдущего ДЗ должны быть перенесены в папку VPN

2018-07-10 20:16 UTC, ValeriyTuev commented
Добрый день. Это в параметрах коммита нужно указать? В параметрах файла я выставил.

2018-07-11 10:13 UTC, Nklya commented
На нормальной ОС типа макоси или линукса атрибуты корретно переносятся с локальной файловой системы.
Если у тебя винда, посмотри что здесь пишут https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows

2018-07-11 20:41 UTC, Nklya commented
А теперь не прописаны хост и порт

<img width="678" alt="image" src="https://user-images.githubusercontent.com/26086394/42598119-ea6992fa-8563-11e8-9743-531e7aef6f1b.png">

2018-07-12 13:44 UTC, Nklya commented
<img width="178" alt="image" src="https://user-images.githubusercontent.com/26086394/42637046-dafc4e04-85f2-11e8-8fd0-3fc8b6cfa12d.png">

Галочки сверху нужно выбирать, галочки снизу не похожи на галочки

2018-07-12 13:53 UTC, Nklya approved these changes
Добрый день.

Валерий, условия ДЗ выполнены, все реализовано хорошо 👍

2018-07-12 13:53 UTC, Nklya commented on VPN/README.md
> +# ValeriyTuev_infra
Зачем еще одино ридми в папке VPN?

2018-07-12 13:53 UTC, Nklya commented on README.md
> +gcloud compute instances create reddit-app\
Такие команды лучше окружать с обоих сторон в тройные кавычки ```, чтобы был блок кода.

2018-07-22 08:49 UTC, merged